language: java
jdk:
  - openjdk12
services:
  - docker
before_install:
  - docker-compose up -d
  - sleep 5
cache:
  directories:
  - $HOME/.m2
install: true
jobs:
  include:
    - stage: build
      if: tag IS NOT present
      script: ./mvnw clean test verify package