language: java
jdk:
  - openjdk13
services:
  - docker
before_install:
  - docker-compose up -d
  - sleep 5
cache:
  directories:
  - $HOME/.m2
addons:
  artifacts: true
install: true
jobs:
  include:
    - stage: build
      if: tag IS NOT present
      script: ./mvnw clean test verify package
    - stage: deploy
      if: tag IS present
      script:
        - cp .mvn.settings.xml $HOME/.m2/settings.xml
        - ./mvnw versions:set -DnewVersion=$TRAVIS_TAG
        - ./mvnw clean test verify package deploy
